services:
  tui_suite:
    build: .
    volumes:
      - docker_cache:/var/lib/docker
      - ssh_keys:/etc/ssh
      - ./.runtimefs:/home/tui_suite/.runtimefs
    privileged: true
    ports:
      - 22:22

volumes:
  docker_cache:
  ssh_keys:
