services:
  tui_suite:
    build: .
    # volumes:
    #   - /var/run/docker.sock:/var/run/docker.sock:ro
    volumes:
      - docker_cache:/var/lib/docker
    privileged: true
    ports:
      - 22:22

volumes:
  docker_cache:
